run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  skip-dirs-use-default: true
  skip-dirs:
    - generated/.*
  modules-download-mode: readonly

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  enable:
    - deadcode
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - goconst
    - gocyclo
    - godox
    - goimports
    - golint
    - gosimple
    - govet
    - ineffassign
    - lll
    - maligned
    - misspell
    - prealloc
    - staticcheck
    - structcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - wsl

linters-settings:
  dupl:
    threshold: 100
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocyclo:
    min-complexity: 15
  govet:
    check-shadowing: true
  lll:
    line-length: 100
  maligned:
    suggest-new: true
  misspell:
    locale: US
  dogsled:
    max-blank-identifiers: 2

issues:
  exclude-rules:
    - linters:
        - lll
      source: "^//go:generate "
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  new-from-rev: d47dcc3
