common: &common
  timeout_in_minutes: 20
  agents:
    queue: workers
  retry:
    # Automatically retry failures one time.
    automatic:
      limit: 1
    # Allow manual retries.
    manual: true

steps:
  - name: "Services, Tools, Metalint"
    command: make clean install-vendor-m3 services tools metalint
    plugins:
      docker-compose#v2.5.1:
        run: app
        workdir: /go/src/github.com/m3db/m3
    <<: *common
  - name: "Check for docker and docs builds :docker: :books:"
    commands:
    - ".ci/docker/check_do_docker.sh"
    - ".buildkite/scripts/check_do_docs.sh"
    agents:
      queue: init
    timeout_in_minutes: 10
    retry:
      automatic:
        limit: 1
      manual: true
