common: &common
  timeout_in_minutes: 20
  agents:
    queue: workers
  retry:
    # Automatically retry failures one time.
    automatic:
      limit: 1
    # Allow manual retries.
    manual: true

steps:
  - name: "Integration (dbnode Recently Read) %n"
    parallelism: 2
    command: make clean install-vendor-m3 test-ci-integration-dbnode cache_policy=recently_read
    plugins:
      docker-compose#v2.5.1:
        run: app
        workdir: /go/src/github.com/m3db/m3
    <<: *common
