version: "3.5"
services:
  m3db_seed:
    networks:
      - backend
    build:
      context: ../../../bin
      dockerfile: ./docker/m3dbnode/development.Dockerfile
    image: m3dbnode:dev
    volumes:
      - "./m3dbnode.yml:/etc/m3dbnode/m3dbnode.yml"
      - "./schema.proto:/etc/m3dbnode/schema.proto"
    environment:
      - M3DB_HOST_ID=m3db_seed
    expose:
      - "2379"
      - "9002"
      - "9003"
      - "9004"
    ports:
      - "0.0.0.0:2379:2379"
      - "0.0.0.0:9002:9002"
      - "0.0.0.0:9003:9003"
      - "0.0.0.0:9004:9004"
  m3db_data01:
    networks:
      - backend
    build:
      context: ../../../bin
      dockerfile: ./docker/m3dbnode/development.Dockerfile
    image: m3dbnode:dev
    volumes:
      - "./m3dbnode.yml:/etc/m3dbnode/m3dbnode.yml"
    environment:
      - M3DB_HOST_ID=m3db_data01
  m3db_data02:
    networks:
      - backend
    build:
      context: ../../../bin
      dockerfile: ./docker/m3dbnode/development.Dockerfile
    image: m3dbnode:dev
    volumes:
      - "./m3dbnode.yml:/etc/m3dbnode/m3dbnode.yml"
    environment:
      - M3DB_HOST_ID=m3db_data02
  m3coordinator01:
    expose:
      - "7201"
      - "7203"
      - "7204"
      - "7507"
    ports:
      - "0.0.0.0:7201:7201"
      - "0.0.0.0:7203:7203"
      - "0.0.0.0:7204:7204"
      - "0.0.0.0:7507:7507"
    networks:
      - backend
    build:
      context: ../../../bin
      dockerfile: ./docker/m3coordinator/development.Dockerfile
    image: m3coordinator:dev
    volumes:
      # Use a git ignored path to easily change pre-set configs.
      # Note: Use ".tmp" suffix is git ignored.
      - "./m3coordinator.yml.tmp:/etc/m3coordinator/m3coordinator.yml"
      - "./schema.proto:/etc/m3coordinator/schema.proto"
  prometheus01:
    expose:
      - "9090"
    ports:
      - "0.0.0.0:9090:9090"
    networks:
      - backend
    image: prom/prometheus:latest
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
  prometheus02:
    expose:
      - "9091"
    ports:
      - "0.0.0.0:9091:9090"
    networks:
      - backend
    image: prom/prometheus:latest
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
  grafana:
    build:
      context: ../../../
      dockerfile: ./docker/grafana/Dockerfile
    expose:
      - "3000"
    ports:
      - "0.0.0.0:3000:3000"
    networks:
      - backend
    image: m3grafana:latest
networks:
  backend:
